### PR TITLE
Fix bookmarks for rails 4.2.1. Fixes #1153

### LINKED ISSUE #1153: Bookmarks fail on rails 4.2.1
```
  1) Bookmark#document should be a SolrDocument with just an id field
     Failure/Error: b.document = SolrDocument.new(id: 'u001')
     NoMethodError:
       undefined method `_read_attribute' for {"id"=>"u001"}:ActiveSupport::HashWithIndifferentAccess
     # ./lib/blacklight/document.rb:55:in `method_missing'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/associations/belongs_to_association.rb:83:in `replace_keys'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/associations/belongs_to_polymorphic_association.rb:13:in `replace_keys'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/associations/belongs_to_association.rb:14:in `replace'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/associations/singular_association.rb:17:in `writer'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/associations/builder/association.rb:123:in `document='
     # ./spec/models/bookmark_spec.rb:7:in `block (2 levels) in <top (required)>'
```

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by jcoyne** [comment]
@cbeer This second commit should fix that last failure

File: app/helpers/blacklight/configuration_helper_behavior.rb [hunk 1]
```diff
@@ -87,13 +87,11 @@ def document_show_field_label document, field
...
+    defaults << field.to_s.humanize
 
-    field_label(
-      :"blacklight.search.fields.facet.#{field}",
-      :"blacklight.search.fields.#{field}",
-      (field_config.label if field_config),
-      field.to_s.humanize
-    )
+    field_label defaults
   end
```
Comment (jrochkind) [inline app/helpers/blacklight/configuration_helper_behavior.rb]: This has changed the semantics when `field_config` is nil (or "falsy").  

In the first version, if `field_config` is falsy, there will be a nil third argument to `field_label`. 

In the new version, if `field_config` is falsy, there will only be three arguments passed to `field_label`, with `field.to_s.humanize` being the third rather than the fourth. 

Was that intended? Is it related to the 4.2.1 breakage somehow?

Comment (cbeer) [inline app/helpers/blacklight/configuration_helper_behavior.rb]: I don't think it matters. Somewhere in the stack, the `nil` values get compacted away.

Comment (jcoyne) [inline app/helpers/blacklight/configuration_helper_behavior.rb]: The nil values usually get compacted, unless you're  on rails 4.2.1, then they raise an error. See rails/rails#19419

**Comment by cbeer** [comment]
Wait, so we're still going to have broken string fallbacks too?

**Comment by cbeer** [comment]
:+1: 

This looks pretty easy to backport. Do you think we should, and if so, how far back?

**Comment by jrochkind** [comment]
@cbeer I am still not ready to deal with deprecation warnings in BL 4.10+, but would love to be able to run on Rails 4.2.1.  So from my perspective, a backport to, I guess, BL 4.9.x would be awesome.
