### PR TITLE
Evaluate blacklight configuration conditionals in an explicit evaluation context, by default the current controller

### LINKED ISSUE #917: Evaluating if/unless with method symbol on add_facet_field evaluates in helper context
While the method is on the controller.

Using this config:
```ruby
  configure_blacklight do |config|
    config.add_facet_field 'private_field', label: "Private", if: :admin?
  end

  def admin?
    true
  end
```

Getting this stacktrace:
```
undefined method `admin?' for class `#<Class:0x007fe7f355fb80>'
blacklight (5.4.0) app/helpers/blacklight/configuration_helper_behavior.rb:168:in `method'
blacklight (5.4.0) app/helpers/blacklight/configuration_helper_behavior.rb:168:in `evaluate_configuration_conditional'
blacklight (5.4.0) app/helpers/blacklight/configuration_helper_behavior.rb:158:in `should_render_field?'
blacklight (5.4.0) app/helpers/blacklight/facets_helper_behavior.rb:63:in `should_render_facet?'
blacklight (5.4.0) app/helpers/blacklight/facets_helper_behavior.rb:41:in `render_facet_limit'
blacklight (5.4.0) app/helpers/blacklight/facets_helper_behavior.rb:24:in `block in render_facet_partials'
blacklight (5.4.0) app/helpers/blacklight/facets_helper_behavior.rb:23:in `map'
blacklight (5.4.0) app/helpers/blacklight/facets_helper_behavior.rb:23:in `render_facet_partials'
blacklight (5.4.0) app/views/catalog/_facets.html.erb:19:in `___sers_justin__rbenv_versions_______lib_ruby_gems_______gems_blacklight_______app_views_catalog__facets_html_erb__4446516814073808986_70317098829420'
actionpack (4.0.5) lib/action_view/template.rb:143:in `block in render'
```

### PR DESCRIPTION
**Pull request by cbeer**
Fixes #917

### CODE REVIEW

File: app/controllers/concerns/blacklight/default_component_configuration.rb [hunk 1]
```diff
@@ -19,6 +19,10 @@ module DefaultComponentConfiguration
       add_nav_action(:search_history, partial: 'blacklight/nav/search_history')
     end
 
+    def render_sms_action? config, options = {}
+      !sms_mappings.blank?
```
Comment (jkeck) [inline app/controllers/concerns/blacklight/default_component_configuration.rb]: `sms_mappings.present?` ?

Comment (jkeck) [inline app/controllers/concerns/blacklight/default_component_configuration.rb]: (Ah, I see that you're just moving this code, feel free to ignore me)

Comment (cbeer) [inline app/controllers/concerns/blacklight/default_component_configuration.rb]: Yeah, let me fix that, though.
