### PR TITLE
Address rubocop and rspec failures

### LINKED ISSUE #3062: CI lint step is failing
Output from CI:

```
Running RuboCop...
RuboCop failed!
Inspecting 347 files
..................................................................................................................................................................................C..............................................................................................C.........................................................................

Offenses:

lib/blacklight/solr/response/group_response.rb:54:22: C: [Correctable] Style/ArgumentsForwarding: Use shorthand syntax ... for arguments forwarding.
  def method_missing meth, *args, &block
                     ^^^^^^^^^^^^^^^^^^^
lib/blacklight/solr/response/group_response.rb:56:21: C: [Correctable] Style/ArgumentsForwarding: Use shorthand syntax ... for arguments forwarding.
      response.send(meth, *args, &block)
                    ^^^^^^^^^^^^^^^^^^^
spec/models/blacklight/configurable_spec.rb:96:51: C: [Correctable] Layout/ExtraSpacing: Unnecessary spacing detected.
      expect(instance.blacklight_config.foo).to eq  "bar"
                                                  ^
spec/models/blacklight/configurable_spec.rb:96:51: C: [Correctable] Layout/SpaceBeforeFirstArg: Put one space between the method name and the first argument.
      expect(instance.blacklight_config.foo).to eq  "bar"
```

It looks like a new feature in Rubocop 1.55.0 and a bug fix in 1.54.2 are to blame.

### PR DESCRIPTION
**Pull request by sandbergja**
closes #3062 

Also addresses [this issue with the webdrivers gem](https://github.com/titusfortner/webdrivers/issues/247#issuecomment-1648154088), by simply removing the gem and relying on selenium-webdriver for this.

### CODE REVIEW

File: lib/blacklight/solr/response/group_response.rb [hunk 1]
```diff
@@ -51,9 +51,9 @@ def entry_name(options)
     )
   end
 
-  def method_missing meth, *args, &block
+  def method_missing(...)
```
Comment (jcoyne) [inline lib/blacklight/solr/response/group_response.rb:54]: Is this compatible with all versions of ruby that we want to support?

Comment (sandbergja) [reply lib/blacklight/solr/response/group_response.rb]: It sure is not 🤣.  I'll put it into .rubocop.yml instead.

**Review by jcoyne — APPROVED** [review]
