### PR TITLE
Use updated capybara filter_block syntax

### LINKED ISSUE #3043: Tests failing with capybara error
Probably this is being caused by a an update to the capybara gem which was released on April 3, 2023

https://github.com/teamcapybara/capybara/blob/master/History.md#version-3390

### PR DESCRIPTION
**Pull request by sandbergja**
https://github.com/teamcapybara/capybara/issues/2616 changed how blocks are evaluated.  Thanks to @maxkadel for finding this change!

Also includes a fix for https://github.com/ViewComponent/view_component/pull/1666

closes #3043

### CODE REVIEW

File: app/components/blacklight/response/pagination_component.rb [hunk 1]
```diff
@@ -8,10 +8,14 @@ class PaginationComponent < Blacklight::Component
       # @param [Hash] html html options for the pagination container
       def initialize(response:, html: {}, **pagination_args)
         @response = response
```
Comment (sandbergja) [inline app/components/blacklight/response/pagination_component.rb:10]: ViewComponents [no longer allows](https://github.com/ViewComponent/view_component/pull/1666) `t()` to be called in an initializer.

File: lib/railties/blacklight.rake [hunk 2]
```diff
@@ -40,7 +40,7 @@ namespace :blacklight do
         exit 1
       end
     rescue => e
-      puts e.to_s
```
Comment (sandbergja) [inline lib/railties/blacklight.rake:43]: New rubocop complaints

File: spec/presenters/blacklight/show_presenter_spec.rb [hunk 3]
```diff
@@ -68,12 +64,10 @@ def mock_document_app_helper_url *args
         tmp_value = Capybara.ignore_hidden_elements
         Capybara.ignore_hidden_elements = false
         document.export_formats.each_pair do |format, _spec|
-          expect(subject).to have_selector("link[href$='.#{format}']") do |matches|
```
Comment (sandbergja) [inline spec/presenters/blacklight/show_presenter_spec.rb:71]: Capybara evaluates blocks differently as of https://github.com/teamcapybara/capybara/issues/2616

Comment (jcoyne) [reply spec/presenters/blacklight/show_presenter_spec.rb:71]: @sandbergja I don't understand. That ticket was closed with no action taken.

Comment (jcoyne) [reply spec/presenters/blacklight/show_presenter_spec.rb:71]: Ah, I see it's https://github.com/teamcapybara/capybara/pull/2617#issuecomment-1368291831 where the change was made.

**Review by jcoyne — APPROVED** [review]
